# Generated by Django 3.1.1 on 2020-09-04 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField()),
                ("html", models.TextField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("publish_date", models.DateField(blank=True, null=True)),
                ("top_image", models.URLField(blank=True, null=True)),
                ("keywords", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
