# Generated by Django 3.1.1 on 2020-09-04 19:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_auto_20200904_1853"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article", old_name="content", new_name="html",
        ),
        migrations.RemoveField(model_name="article", name="id",),
        migrations.AddField(
            model_name="article",
            name="publish_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="top_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
