# Generated by Django 3.1.1 on 2020-09-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_auto_20200904_1914"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="tags",),
    ]
