# Generated by Django 3.1.1 on 2020-09-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_remove_article_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="keywords",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="publish_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
